
name: Build

on:
  pull_request:
    branches:
      "master"
  push:
    branches:
      "master"

jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      - uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: https://allure.autotests.cloud
          allure-token: ${{ secrets.ALLURE_TOKEN }}
          allure-project-id: 2214
      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v2
      - run: allurectl watch -- ./gradlew clean test
        env:
          ALLURE_RESULTS: build/allure-results


